In [82]:
import pandas as pd

df = pd.read_csv("../data/ravenstack_accounts.csv")
df.shape

(500, 10)

In [5]:
df.columns

Index(['account_id', 'account_name', 'industry', 'country', 'signup_date',
       'referral_source', 'plan_tier', 'seats', 'is_trial', 'churn_flag'],
      dtype='str')

In [6]:
df.dtypes

account_id           str
account_name         str
industry             str
country              str
signup_date          str
referral_source      str
plan_tier            str
seats              int64
is_trial            bool
churn_flag          bool
dtype: object

In [7]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    str
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), int64(1), str(7)
memory usage: 32.4 KB

In [8]:
df.nunique()

account_id         500
account_name       500
industry             5
country              7
signup_date        370
referral_source      5
plan_tier            3
seats               73
is_trial             2
churn_flag           2
dtype: int64

In [9]:
print("Industries:")
print(df["industry"].unique())

print("\nCountries:")
print(df["country"].unique())

print("\nReferral Sources:")
print(df["referral_source"].unique())

print("\nPlan Tiers:")
print(df["plan_tier"].unique())

Industries:
<StringArray>
['EdTech', 'FinTech', 'DevTools', 'HealthTech', 'Cybersecurity']
Length: 5, dtype: str

Countries:
<StringArray>
['US', 'IN', 'UK', 'CA', 'DE', 'AU', 'FR']
Length: 7, dtype: str

Referral Sources:
<StringArray>
['partner', 'other', 'organic', 'event', 'ads']
Length: 5, dtype: str

Plan Tiers:
<StringArray>
['Basic', 'Enterprise', 'Pro']
Length: 3, dtype: str

In [10]:
df["churn_flag"].value_counts()

churn_flag
False    390
True     110
Name: count, dtype: int64

In [11]:
df["seats"].describe()

count    500.000000
mean      20.560000
std       21.044718
min        1.000000
25%        5.000000
50%       15.000000
75%       28.000000
max      163.000000
Name: seats, dtype: float64

In [12]:
df.isnull().sum()

account_id         0
account_name       0
industry           0
country            0
signup_date        0
referral_source    0
plan_tier          0
seats              0
is_trial           0
churn_flag         0
dtype: int64

In [13]:
df.duplicated().sum()

np.int64(0)

In [15]:
df["signup_date"] = pd.to_datetime(df["signup_date"])

In [16]:
df.info()

<class 'pandas.DataFrame'>
RangeIndex: 500 entries, 0 to 499
Data columns (total 10 columns):
 #   Column           Non-Null Count  Dtype
---  ------           --------------  -----
 0   account_id       500 non-null    str
 1   account_name     500 non-null    str
 2   industry         500 non-null    str
 3   country          500 non-null    str
 4   signup_date      500 non-null    datetime64[us]
 5   referral_source  500 non-null    str
 6   plan_tier        500 non-null    str
 7   seats            500 non-null    int64
 8   is_trial         500 non-null    bool
 9   churn_flag       500 non-null    bool
dtypes: bool(2), datetime64[us](1), int64(1), str(6)
memory usage: 32.4 KB

In [17]:
for col in ["industry", "country", "referral_source", "plan_tier"]:
    print(f"\n{col}:")
    print(df[col].value_counts())

industry:
industry
DevTools         113
FinTech          112
Cybersecurity    100
HealthTech        96
EdTech            79
Name: count, dtype: int64

country:
country
US    291
UK     58
IN     49
AU     32
DE     25
CA     23
FR     22
Name: count, dtype: int64

referral_source:
referral_source
organic    114
other      103
ads         98
event       96
partner     89
Name: count, dtype: int64

plan_tier:
plan_tier
Pro           178
Basic         168
Enterprise    154
Name: count, dtype: int64

In [18]:
df[df["seats"] <= 0]

Empty DataFrame
Columns: [account_id, account_name, industry, country, signup_date, referral_source, plan_tier, seats, is_trial, churn_flag]
Index: []

In [19]:
print("Earliest signup:", df["signup_date"].min())
print("Latest signup:", df["signup_date"].max())

Earliest signup: 2023-01-02 00:00:00
Latest signup: 2024-12-31 00:00:00

In [20]:
id_check = df["account_id"].nunique()

print("Total rows:", len(df))
print("Unique account IDs:", id_check)

Total rows: 500
Unique account IDs: 500

In [21]:
df.shape

(500, 10)

In [22]:
churn_rate = df["churn_flag"].mean()

print(f"Overall churn rate: {churn_rate:.1%}")

Overall churn rate: 22.0%

In [23]:
df.groupby("plan_tier")["churn_flag"].mean()

plan_tier
Basic         0.220238
Enterprise    0.220779
Pro           0.219101
Name: churn_flag, dtype: float64

In [24]:
df.groupby("industry")["churn_flag"].mean()

industry
Cybersecurity    0.160000
DevTools         0.309735
EdTech           0.164557
FinTech          0.223214
HealthTech       0.218750
Name: churn_flag, dtype: float64

In [25]:
pd.crosstab(df["industry"], df["churn_flag"])

churn_flag     False  True
industry
Cybersecurity     84     16
DevTools          78     35
EdTech            66     13
FinTech           87     25
HealthTech        75     21

In [26]:
df.groupby("is_trial")["churn_flag"].mean()

is_trial
False    0.210918
True     0.257732
Name: churn_flag, dtype: float64

In [27]:
df.groupby("country")["churn_flag"].mean()

country
AU    0.125000
CA    0.173913
DE    0.320000
FR    0.227273
IN    0.204082
UK    0.189655
US    0.233677
Name: churn_flag, dtype: float64

In [28]:
pd.crosstab(df["country"], df["churn_flag"])

churn_flag  False  True
country
AU             28      4
CA             19      4
DE             17      8
FR             17      5
IN             39     10
UK             47     11
US            223     68

In [29]:
df.groupby("churn_flag")["seats"].mean()

churn_flag
False    20.933333
True     19.236364
Name: seats, dtype: float64

In [30]:
df.groupby("churn_flag")["seats"].median()

churn_flag
False    15.0
True     13.5
Name: seats, dtype: float64

In [31]:
df.groupby(df["signup_date"].dt.year)["churn_flag"].mean()

signup_date
2023    0.255507
2024    0.190476
Name: churn_flag, dtype: float64

In [34]:
df["signup_year"] = df["signup_date"].dt.year

In [35]:
df[["signup_date", "signup_year"]].head()

  signup_date  signup_year
0  2024-10-16         2024
1  2023-08-17         2023
2  2024-08-27         2024
3  2023-08-27         2023
4  2024-10-27         2024

In [36]:
reference_date = df["signup_date"].max()

print("Reference date:", reference_date)

Reference date: 2024-12-31 00:00:00

In [37]:
df["tenure_days"] = (reference_date - df["signup_date"]).dt.days

In [38]:
df[["signup_date", "tenure_days"]].head()

  signup_date  tenure_days
0  2024-10-16           76
1  2023-08-17          502
2  2024-08-27          126
3  2023-08-27          492
4  2024-10-27           65

In [39]:
df["signup_month"] = df["signup_date"].dt.month

In [40]:
df[["signup_date", "signup_month"]].head()

  signup_date  signup_month
0  2024-10-16            10
1  2023-08-17             8
2  2024-08-27             8
3  2023-08-27             8
4  2024-10-27            10

In [41]:
df["signup_day"] = df["signup_date"].dt.day_name()

In [42]:
df[["signup_date", "signup_day"]].head()

  signup_date signup_day
0  2024-10-16  Wednesday
1  2023-08-17   Thursday
2  2024-08-27    Tuesday
3  2023-08-27     Sunday
4  2024-10-27     Sunday

In [43]:
X = df[
    [
        "industry",
        "country",
        "referral_source",
        "plan_tier",
        "seats",
        "is_trial",
        "signup_year",
        "signup_month",
        "signup_day",
        "tenure_days"
    ]
]

y = df["churn_flag"]

print("X shape:", X.shape)
print("y shape:", y.shape)

X shape: (500, 10)
y shape: (500,)

In [44]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (400, 10)
X_test: (100, 10)
y_train: (400,)
y_test: (100,)

In [45]:
%pip install scikit-learn

Requirement already satisfied: scikit-learn in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (1.9.1)
Requirement already satisfied: numpy>=1.24.1 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from scikit-learn) (2.5.2)
Requirement already satisfied: scipy>=1.10.0 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from scikit-learn) (1.18.1)
Requirement already satisfied: joblib>=1.4.0 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from scikit-learn) (1.6.0)
Requirement already satisfied: narwhals>=2.0.1 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from scikit-learn) (2.26.0)
Requirement already satisfied: threadpoolctl>=3.5.0 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from scikit-learn) (3.7.0)
Requirement already satisfied: cloudpickle>=3.0 in C:\Users\Mr Moses\conda-envs\datascience\Lib\site-packages (from joblib>=1.4.0->scikit-learn) (3.1.2)
Note: you may need to restart the kernel to use updated packages.

In [46]:
from sklearn.model_selection import train_test_split

X_train, X_test, y_train, y_test = train_test_split(
    X,
    y,
    test_size=0.20,
    random_state=42,
    stratify=y
)

print("X_train:", X_train.shape)
print("X_test:", X_test.shape)
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

X_train: (400, 10)
X_test: (100, 10)
y_train: (400,)
y_test: (100,)

In [47]:
categorical_features = [
    "industry",
    "country",
    "referral_source",
    "plan_tier",
    "signup_day"
]

numerical_features = [
    "seats",
    "signup_year",
    "signup_month",
    "tenure_days"
]

print("Categorical features:", categorical_features)
print("Numerical features:", numerical_features)

Categorical features: ['industry', 'country', 'referral_source', 'plan_tier', 'signup_day']
Numerical features: ['seats', 'signup_year', 'signup_month', 'tenure_days']

In [48]:
from sklearn.preprocessing import OneHotEncoder

encoder = OneHotEncoder(
    handle_unknown="ignore",
    sparse_output=False
)

In [49]:
encoder.fit(X_train[categorical_features])

OneHotEncoder(handle_unknown='ignore', sparse_output=False)

In [50]:
X_train_encoded = encoder.transform(X_train[categorical_features])
X_test_encoded = encoder.transform(X_test[categorical_features])

print("X_train_encoded:", X_train_encoded.shape)
print("X_test_encoded:", X_test_encoded.shape)

X_train_encoded: (400, 27)
X_test_encoded: (100, 27)

In [51]:
X_train_numeric = X_train[numerical_features].to_numpy()
X_test_numeric = X_test[numerical_features].to_numpy()

print("X_train_numeric:", X_train_numeric.shape)
print("X_test_numeric:", X_test_numeric.shape)

X_train_numeric: (400, 4)
X_test_numeric: (100, 4)

In [52]:
import numpy as np

X_train_processed = np.hstack([
    X_train_numeric,
    X_train_encoded
])

X_test_processed = np.hstack([
    X_test_numeric,
    X_test_encoded
])

print("X_train_processed:", X_train_processed.shape)
print("X_test_processed:", X_test_processed.shape)

X_train_processed: (400, 31)
X_test_processed: (100, 31)

In [53]:
print("y_train:", y_train.shape)
print("y_test:", y_test.shape)

print("\nChurn distribution in training data:")
print(y_train.value_counts())

y_train: (400,)
y_test: (100,)

Churn distribution in training data:
churn_flag
False    312
True      88
Name: count, dtype: int64

In [54]:
y_train_array = y_train.to_numpy()
y_test_array = y_test.to_numpy()

print("y_train_array:", y_train_array.shape)
print("y_test_array:", y_test_array.shape)

y_train_array: (400,)
y_test_array: (100,)

In [55]:
print("Training data:", X_train_processed.shape, y_train_array.shape)
print("Testing data:", X_test_processed.shape, y_test_array.shape)

Training data: (400, 31) (400,)
Testing data: (100, 31) (100,)

In [56]:
from sklearn.linear_model import LogisticRegression

In [57]:
model = LogisticRegression(
    max_iter=1000,
    random_state=42
)

In [58]:
model.fit(
    X_train_processed,
    y_train_array
)

LogisticRegression(max_iter=1000, random_state=42)

In [59]:
y_pred = model.predict(X_test_processed)

print("Predictions:", y_pred[:10])
print("Number of predictions:", len(y_pred))

Predictions: [False False False False False False False False False False]
Number of predictions: 100

In [60]:
from sklearn.metrics import accuracy_score

accuracy = accuracy_score(y_test_array, y_pred)

print("Baseline Accuracy:", accuracy)

Baseline Accuracy: 0.79

In [61]:
from sklearn.metrics import confusion_matrix

cm = confusion_matrix(y_test_array, y_pred)

print("Confusion Matrix:")
print(cm)

Confusion Matrix:
[[77  1]
 [20  2]]

In [62]:
from sklearn.metrics import precision_score, recall_score

precision = precision_score(y_test_array, y_pred)
recall = recall_score(y_test_array, y_pred)

print("Precision:", precision)
print("Recall:", recall)

Precision: 0.6666666666666666
Recall: 0.09090909090909091

In [63]:
from sklearn.ensemble import RandomForestClassifier

In [64]:
rf_model = RandomForestClassifier(
    n_estimators=100,
    random_state=42
)

In [65]:
rf_model.fit(
    X_train_processed,
    y_train_array
)

RandomForestClassifier(random_state=42)

In [66]:
rf_pred = rf_model.predict(X_test_processed)

print("Predictions:", rf_pred[:10])
print("Number of predictions:", len(rf_pred))

Predictions: [False False False False False False False False False False]
Number of predictions: 100

In [67]:
rf_accuracy = accuracy_score(
    y_test_array,
    rf_pred
)

print("Random Forest Accuracy:", rf_accuracy)

Random Forest Accuracy: 0.79

In [68]:
rf_cm = confusion_matrix(
    y_test_array,
    rf_pred
)

print("Random Forest Confusion Matrix:")
print(rf_cm)

Random Forest Confusion Matrix:
[[76  2]
 [19  3]]

In [69]:
rf_precision = precision_score(
    y_test_array,
    rf_pred
)

rf_recall = recall_score(
    y_test_array,
    rf_pred
)

print("Random Forest Precision:", rf_precision)
print("Random Forest Recall:", rf_recall)

Random Forest Precision: 0.6
Random Forest Recall: 0.13636363636363635

In [70]:
model_comparison = pd.DataFrame({
    "Model": ["Logistic Regression", "Random Forest"],
    "Accuracy": [accuracy, rf_accuracy],
    "Precision": [precision, rf_precision],
    "Recall": [recall, rf_recall]
})

model_comparison

                 Model  Accuracy  Precision    Recall
0  Logistic Regression      0.79   0.666667  0.090909
1        Random Forest      0.79   0.600000  0.136364

In [71]:
rf_probabilities = rf_model.predict_proba(X_test_processed)

print("Probability shape:", rf_probabilities.shape)
print(rf_probabilities[:5])

Probability shape: (100, 2)
[[0.71 0.29]
 [0.95 0.05]
 [0.8  0.2 ]
 [0.8  0.2 ]
 [0.86 0.14]]

In [72]:
churn_probability = rf_probabilities[:, 1]

print("First 10 churn probabilities:")
print(churn_probability[:10])

First 10 churn probabilities:
[0.29 0.05 0.2  0.2  0.14 0.39 0.29 0.27 0.21 0.32]

In [73]:
risk_df = df.loc[
    X_test.index,
    [
        "account_id",
        "account_name",
        "industry",
        "country",
        "plan_tier",
        "seats",
        "is_trial"
    ]
].copy()

risk_df["churn_probability"] = churn_probability

risk_df = risk_df.sort_values(
    "churn_probability",
    ascending=False
)

risk_df.head(10)

,account_id,account_name,industry,country,plan_tier,seats,is_trial,churn_probability
484,A-e1b9cd,Company_484,DevTools,US,Pro,40,False,0.60
71,A-9b9fe9,Company_71,EdTech,AU,Basic,5,False,0.57
18,A-c4ea60,Company_18,FinTech,DE,Enterprise,18,False,0.57
234,A-e89151,Company_234,FinTech,UK,Pro,8,True,0.56
2,A-0a282f,Company_2,DevTools,US,Basic,1,False,0.51
120,A-65aeb5,Company_120,DevTools,US,Pro,9,False,0.47
429,A-7641d3,Company_429,EdTech,US,Pro,8,True,0.46
354,A-b54c01,Company_354,DevTools,US,Enterprise,29,False,0.46
158,A-d5a319,Company_158,FinTech,US,Enterprise,15,False,0.46
231,A-de24d5,Company_231,DevTools,US,Enterprise,5,True,0.44

In [74]:
high_risk_customers = risk_df[
    risk_df["churn_probability"] >= 0.50
].copy()

print("Number of high-risk customers:", len(high_risk_customers))

high_risk_customers

Number of high-risk customers: 5

,account_id,account_name,industry,country,plan_tier,seats,is_trial,churn_probability
484,A-e1b9cd,Company_484,DevTools,US,Pro,40,False,0.60
71,A-9b9fe9,Company_71,EdTech,AU,Basic,5,False,0.57
18,A-c4ea60,Company_18,FinTech,DE,Enterprise,18,False,0.57
234,A-e89151,Company_234,FinTech,UK,Pro,8,True,0.56
2,A-0a282f,Company_2,DevTools,US,Basic,1,False,0.51

In [76]:
import os
print(os.getcwd())
print(os.listdir("../data"))

C:\Users\Mr Moses\Downloads\SaaS_Churn_Project_5\notebooks
['ravenstack_accounts.csv.csv']

In [81]:
import os

print(os.path.abspath("../data/ravenstack_accounts.csv"))
print(os.path.exists("../data/ravenstack_accounts.csv"))

C:\Users\Mr Moses\Downloads\SaaS_Churn_Project_5\data\ravenstack_accounts.csv
False